linkedin_profile = {
    "public_identifier": "eden-marco",
    "profile_pic_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/person/eden-marco/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20230415%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20230415T060723Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=cbf1d19573aeaa7d59764cb970048438fe039152c8a6cd9f961e5c2d93e58bf4",
    "background_cover_image_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/person/eden-marco/cover?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20230415%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20230415T060723Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=fc415e09624beaefc2739897951a2a0f7217661748f1acf0f26129b1364612df",
    "first_name": "Eden",
    "last_name": "Marco",
    "full_name": "Eden Marco",
    "follower_count": None,
    "occupation": "Software Engineer at Orca Security",
    "headline": "Software Engineer @ Orca Security | Best-selling Udemy Instructor",
    "summary": "Backend developer, Udemy.com best seller instructor",
    "country": "IL",
    "country_full_name": "Israel",
    "city": "Tel Aviv",
    "state": None,
    "experiences": [
        {
            "starts_at": {"day": 1, "month": 4, "year": 2020},
            "ends_at": None,
            "company": "Orca Security",
            "company_linkedin_profile_url": "https://il.linkedin.com/company/orca-security",
            "title": "Software Engineer",
            "description": None,
            "location": "Tel Aviv, Israel",
            "logo_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/company/orca-security/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20230415%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20230415T060723Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=40123c48a5ed0c84b3a0d46aff832d9da3f43d9ad323b6956aa84e8a2d8647e4",
        },
        {
            "starts_at": {"day": 1, "month": 12, "year": 2019},
            "ends_at": {"day": 30, "month": 4, "year": 2020},
            "company": "Wizer",
            "company_linkedin_profile_url": "https://il.linkedin.com/company/get-wizer",
            "title": "Software Engineer",
            "description": None,
            "location": "Tel Aviv Area, Israel",
            "logo_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/company/get-wizer/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20230415%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20230415T060723Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=9ed4d7474ba3989f0f1b66347ce4041ad58c3bdc9db237ee4f14287e2b70ead4",
        },
        {
            "starts_at": {"day": 1, "month": 7, "year": 2019},
            "ends_at": {"day": 31, "month": 12, "year": 2019},
            "company": "Deep Instinct",
            "company_linkedin_profile_url": "https://il.linkedin.com/company/deep-instinct",
            "title": "Software Engineer",
            "description": "* Functional Programming (Including international school)\n* Introduction to Computer Science",
            "location": "Tel Aviv Area, Israel",
            "logo_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/company/deep-instinct/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20230415%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20230415T060723Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=e618355cd74dc6dac1a11a57ab96bb7e8b46717aaf9572a1169cf0f2c34c694c",
        },
        {
            "starts_at": {"day": 1, "month": 10, "year": 2018},
            "ends_at": {"day": 31, "month": 7, "year": 2019},
            "company": "Reichman University (IDC Herzliya)",
            "company_linkedin_profile_url": "https://il.linkedin.com/company/reichman-university-idc-herzliya",
            "title": "Computer Science Teaching Assistant (External Lecturer)",
            "description": "* Functional Programming (Including international school)\n* Introduction to Computer Science",
            "location": "Herzliya Area, Israel",
            "logo_url": "https://media-exp1.licdn.com/dms/image/C4D0BAQGg9wJflAQnjw/company-logo_100_100/0/1632054179547?e=1659571200&v=beta&t=iCDKtMk_jscA7MarBSvl7jjRicr3GidJdKGK_q94uL8",
        },
        {
            "starts_at": {"day": 1, "month": 2, "year": 2017},
            "ends_at": None,
            "company": "Udemy",
            "company_linkedin_profile_url": "https://il.linkedin.com/company/udemy",
            "title": "Independent Udemy Instructor",
            "description": "Production and publication of two best-selling courses on the Udemy platform, with a total of 7k+ enrolled students, 500+ ratings and a solid 4.7 ★ rating.",
            "location": "Herzliya Area, Israel",
            "logo_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/company/udemy/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20230415%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20230415T060723Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=099f92482b3a40cb3aea1b004b542033906304d594322bfee0ad04a0d42198d1",
        },
        {
            "starts_at": {"day": 1, "month": 7, "year": 2010},
            "ends_at": {"day": 31, "month": 8, "year": 2014},
            "company": "Israel Defense Forces",
            "company_linkedin_profile_url": "https://il.linkedin.com/company/israeldefenseforces",
            "title": "Captain",
            "description": None,
            "location": "Tel Aviv Area, Israel",
            "logo_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/company/israeldefenseforces/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20230415%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20230415T060723Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=6e5d288ddb7e711cd23148b6d85a4a62ec7d8d7acedf921f545322a1ddedf893",
        },
    ],
    "education": [
        {
            "starts_at": {"day": 1, "month": 1, "year": 2015},
            "ends_at": {"day": 31, "month": 12, "year": 2019},
            "field_of_study": "Computer Science",
            "degree_name": "Bachelor’s Degree",
            "school": "Technion - Israel Institute of Technology",
            "school_linkedin_profile_url": "https://il.linkedin.com/school/technion/",
            "description": None,
            "logo_url": "https://media-exp1.licdn.com/dms/image/C4D0BAQG12formuFdJg/company-logo_100_100/0/1559649766994?e=1659571200&v=beta&t=TQzJx39PAqP1-KkVTQxuJErE4_FAltWPPtGcAAV-V_I",
            "grade": None,
            "activities_and_societies": None,
        }
    ],
    "languages": [],
    "accomplishment_organisations": [],
    "accomplishment_publications": [],
    "accomplishment_honors_awards": [],
    "accomplishment_patents": [],
    "accomplishment_courses": [],
    "accomplishment_projects": [],
    "accomplishment_test_scores": [],
    "volunteer_work": [],
    "certifications": [],
    "connections": 500,
    "people_also_viewed": [],
    "recommendations": [],
    "activities": [
        {
            "title": "Introducing Ox4Shell our #opensource project, offering a free #payload deobfuscation tool. Ox4Shell can help the global #appsec community to…",
            "link": "https://www.linkedin.com/signup/cold-join",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "Yay 🥳 I received the 2021 GitHub Actions Hackathon Participant badge!#GitHub #DevTo #Community",
            "link": "https://www.linkedin.com/signup/cold-join",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "With 2022 on the horizon, here are my cloud compliance recommendations for 2022. Hint: Companies need tools that can discover where PII is stored…",
            "link": "https://www.linkedin.com/signup/cold-join",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "Nice blog on how to optimize different Redis client libraries to achieve better performance, as well as several best practices. Much recommended for…",
            "link": "https://www.linkedin.com/signup/cold-join",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "האקתון בלוקצ'יין - משנים את פני שוק ההון הישראלי🇮🇱יומיים של מרתון בהשתתפות אגף החשב הכללי במשרד האוצר, יוצא לדרך!במסגרת ההאקתון ינסו המשתתפים…",
            "link": "https://www.linkedin.com/signup/cold-join",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "I'm looking for a marketing designer to join my design team at Win Brands Group. Great place to work, learn and grow. Share with friends, apply…",
            "link": "https://www.linkedin.com/signup/cold-join",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "You've got to listen to this episode of #LastWeekinAWS with Orca Security CTO, Yoav Alon where he reveals Orca's 3 principles of security that help…",
            "link": "https://il.linkedin.com/posts/ericgold_leading-the-cloud-security-pack-with-yoav-share-6927301506232647680-KFDb",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "YL Ventures congratulates its portfolio company Cycode for being selected among the 10 finalists of the RSA Conference Innovation Sandbox Contest…",
            "link": "https://il.linkedin.com/posts/leitersdorf_yl-ventures-congratulates-its-portfolio-company-share-6927297658231357440-9Juf",
            "activity_status": "Liked by Eden Marco",
        },
        {
            "title": "Amazing news, kudos Dean Bitan and team!Massive impact in benefiting healthcare.A startup to watch out for :)",
            "link": "https://il.linkedin.com/posts/ctech-by-calcalist_larry-ellison-leads-215-million-series-share-6926856825338224640-6ZDe",
            "activity_status": "Liked by Eden Marco",
        },
    ],
    "similarly_named_profiles": [
        {
            "name": "Blumeden Marco Pasquali",
            "link": "https://it.linkedin.com/in/blumeden-marco-pasquali-44603287",
            "summary": "--",
            "location": "Italy",
        },
        {
            "name": "Eden Marco",
            "link": "https://www.linkedin.com/in/edenmarco",
            "summary": "Incoming Deloitte Strategy Summer Scholar",
            "location": "Chapel Hill, NC",
        },
        {
            "name": "Eden Marco",
            "link": "https://www.linkedin.com/in/eden-marco-8299301ba",
            "summary": "Student at San Francisco State University",
            "location": "San Francisco Bay Area",
        },
        {
            "name": "Eden Marco",
            "link": "https://www.linkedin.com/in/eden-marco-875211201",
            "summary": "Incoming First Year Optometry Student at Massachusetts College of Pharmacy & Health Sciences",
            "location": "Greater Boston",
        },
    ],
    "articles": [],
    "groups": [],
    "phone_numbers": [],
    "social_networking_services": [],
    "skills": [],
    "inferred_salary": None,
    "gender": None,
    "birth_date": None,
    "industry": None,
    "extra": None,
    "interests": [],
    "personal_emails": [],
    "personal_numbers": [],
}
